/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves.h"

bool_t
xdr_Coord (XDR *xdrs, Coord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->value2, MAX_VECTOR,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_res_vector2 (XDR *xdrs, res_vector2 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->value2_len))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->value2_val, sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_response (XDR *xdrs, get_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STRING))
		 return FALSE;
	 if (!xdr_res_vector2 (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_Coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
