/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server_rpc.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, MAX_STRING))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, MAX_STRING))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, MAX_STRING))
		 return FALSE;
	return TRUE;
}
