/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "server_rpc.h"

/*void *
rpc_operation_1_svc(data *argp, struct svc_req *rqstp)
{
	//static char * result;

	printf("%s %s %s\n", argp -> username, argp -> operation, argp -> timestamp);
    fflush(stdout);
    return (void *)TRUE;

	//return (void *) &result;
}*/

void *rpc_operation_1_svc(data *operation_data, struct svc_req *rqstp) {
    printf("%s\t%s\t%s\n", operation_data->username, operation_data->operation, operation_data->timestamp);
    return (void *)TRUE;  // O lo que devuelvas como respuesta
}