/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_RPC_H_RPCGEN
#define _SERVER_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRING 255

struct data {
	char *username;
	char *operation;
	char *timestamp;
};
typedef struct data data;

#define SERVER_RPC_PROG 99
#define SERVER_RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_operation 1
extern  void * rpc_operation_1(data *, CLIENT *);
extern  void * rpc_operation_1_svc(data *, struct svc_req *);
extern int server_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_operation 1
extern  void * rpc_operation_1();
extern  void * rpc_operation_1_svc();
extern int server_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_RPC_H_RPCGEN */
